use crate::tir::*;
use crate::types::Ty;

/// Tracks constructor info for code generation.
struct CodeGen {
    /// (con_name, type_name, variant_index, total, is_enum)
    constructors: Vec<(String, String, usize, usize, bool)>,
    /// Newtype constructor names (identity at runtime)
    newtypes: Vec<String>,
    /// Names that have been forward-declared (skip `local` on definition)
    forward_declared: std::collections::HashSet<String>,
    output: String,
    indent: usize,
}

impl CodeGen {
    fn new() -> Self {
        CodeGen {
            constructors: Vec::new(), newtypes: Vec::new(),
            forward_declared: std::collections::HashSet::new(),
            output: String::new(), indent: 0,
        }
    }

    fn is_newtype(&self, name: &str) -> bool {
        self.newtypes.iter().any(|n| n == name)
    }

    /// Returns "local function name" or "name = function" depending on
    /// whether the name was forward-declared.
    fn fn_decl(&self, lua_name: &str, params: &str) -> String {
        if self.forward_declared.contains(lua_name) {
            format!("{} = function({})", lua_name, params)
        } else {
            format!("local function {}({})", lua_name, params)
        }
    }

    /// Returns "local name = " or "name = " depending on forward declaration.
    fn var_decl(&self, lua_name: &str) -> String {
        if self.forward_declared.contains(lua_name) {
            format!("{} = ", lua_name)
        } else {
            format!("local {} = ", lua_name)
        }
    }

    fn emit(&mut self, s: &str) { self.output.push_str(s); }
    fn emit_indent(&mut self) { for _ in 0..self.indent { self.output.push_str("    "); } }
    fn emit_line(&mut self, s: &str) { self.emit_indent(); self.output.push_str(s); self.output.push('\n'); }

    fn constructor_info(&self, name: &str) -> Option<(usize, usize, bool)> {
        for (cn, _, idx, total, is_enum) in &self.constructors {
            if cn == name { return Some((*idx, *total, *is_enum)); }
        }
        None
    }

    fn register_data_type(&mut self, def: &TDataDef) {
        let is_enum = def.constructors.iter().all(|c| matches!(&c.fields, TConFields::Positional(f) if f.is_empty()));
        for (i, con) in def.constructors.iter().enumerate() {
            self.constructors.push((con.name.clone(), def.name.clone(), i + 1, def.constructors.len(), is_enum));
        }
    }

    fn generate_module(&mut self, module: &TModule) {
        self.emit_line("-- Generated by MATA-LL compiler (https://github.com/hce/mata-ll)");
        self.emit_line("");

        for def in &module.data_defs {
            self.register_data_type(def);
        }
        self.newtypes = module.newtypes.clone();

        // Emit constructors
        for def in &module.data_defs {
            self.gen_data_constructors(def);
        }

        // Emit newtype constructors (identity functions)
        for name in &module.newtypes {
            self.emit_line(&format!("local function {}(_v) return _v end", name));
        }
        if !module.newtypes.is_empty() {
            self.emit_line("");
        }

        // Emit instance method functions
        if !module.instance_fns.is_empty() {
            self.emit_line("-- Typeclass instances");
        }
        for func in &module.instance_fns {
            self.gen_function(func);
        }

        // Emit record field accessors
        if !module.record_accessors.is_empty() {
            self.emit_line("-- Record accessors");
            for (name, idx) in &module.record_accessors {
                self.emit_line(&format!(
                    "local function {}(_r) return _r[{}] end",
                    sanitize_name(name), idx
                ));
            }
            self.emit_line("");
        }

        // Forward-declare all user functions to support mutual recursion
        let user_fn_names: Vec<String> = module.functions.iter()
            .filter(|f| !f.specialized)
            .map(|f| sanitize_name(&f.name))
            .collect();
        if user_fn_names.len() > 1 {
            self.emit_line(&format!("local {}", user_fn_names.join(", ")));
            for name in &user_fn_names {
                self.forward_declared.insert(name.clone());
            }
        }

        // Emit functions (main last, so specializations are defined before use)
        let mut main_fn = None;
        for func in &module.functions {
            if func.name == "main" {
                main_fn = Some(func);
            } else {
                self.gen_function(func);
            }
        }
        if let Some(func) = main_fn {
            self.gen_function(func);
        }

        if module.has_main {
            self.emit_line("");
            self.emit_line("-- Entry point");
            self.emit_line("__run()");
        }

        // Generate module return table for exports
        if !module.exports.is_empty() {
            self.emit_line("");
            self.emit_line("-- Exports");
            self.emit_indent();
            self.emit("return {\n");
            self.indent += 1;
            for name in &module.exports {
                self.emit_indent();
                self.emit(&format!("{} = {},\n", name, sanitize_name(name)));
            }
            self.indent -= 1;
            self.emit_line("}");
        }
    }

    fn gen_data_constructors(&mut self, def: &TDataDef) {
        let is_enum = def.constructors.iter().all(|c| matches!(&c.fields, TConFields::Positional(f) if f.is_empty()));
        let single = def.constructors.len() == 1;

        for (i, con) in def.constructors.iter().enumerate() {
            let tag = i + 1;
            let field_count = match &con.fields {
                TConFields::Positional(f) => f.len(),
                TConFields::Named(f) => f.len(),
            };

            if field_count == 0 {
                if is_enum {
                    self.emit_line(&format!("local {} = {}", con.name, tag));
                } else {
                    self.emit_line(&format!("local {} = {{{}}}", con.name, tag));
                }
            } else {
                let params: Vec<String> = (0..field_count).map(|i| format!("_p{}", i)).collect();
                let params_str = params.join(", ");
                if single {
                    self.emit_line(&format!("local {} = function({}) return {{{}}} end", con.name, params_str, params_str));
                } else {
                    let mut entries = vec![format!("{}", tag)];
                    entries.extend(params.iter().cloned());
                    self.emit_line(&format!("local {} = function({}) return {{{}}} end", con.name, params_str, entries.join(", ")));
                }
            }
        }
        self.emit_line("");
    }

    fn gen_function(&mut self, func: &TFunction) {
        let lua_name = sanitize_name(&func.name);
        let clauses = &func.clauses;

        if clauses.is_empty() { return; }

        if clauses.len() == 1 && clauses[0].patterns.is_empty() && clauses[0].guards.is_empty() {
            // Check if this is a value binding (non-function type) or a
            // zero-arg function (IO action / thunk)
            let is_io_action = matches!(&func.ty, Ty::IO(_) | Ty::LuaIO(_, _) | Ty::Forall(_, _));
            let is_do_block = matches!(&clauses[0].body.kind, TExprKind::Do(_));

            if is_io_action || is_do_block {
                // Wrap in a function (IO action, needs to be called)
                self.emit_indent();
                self.emit(&self.fn_decl(&lua_name, ""));
                self.emit("\n");
                self.indent += 1;
                self.gen_where_binds(&clauses[0].where_binds);
                if is_do_block {
                    self.gen_expr(&clauses[0].body);
                } else {
                    self.emit_indent(); self.emit("return "); self.gen_expr(&clauses[0].body); self.emit("\n");
                }
                self.indent -= 1;
                self.emit_line("end");
            } else if expr_references_name(&clauses[0].body, &func.name) {
                // Self-referencing value binding (e.g., infinite list)
                if !self.forward_declared.contains(&lua_name) {
                    self.emit_line(&format!("local {}", lua_name));
                }
                self.emit_indent();
                self.emit(&format!("{} = ", lua_name));
                self.gen_expr_lazy(&clauses[0].body, &func.name);
                self.emit("\n");
            } else {
                // Simple value binding
                self.emit_indent();
                self.emit(&self.var_decl(&lua_name));
                self.gen_expr(&clauses[0].body);
                self.emit("\n");
            }
            self.emit_line("");
            return;
        }

        if clauses.len() == 1 && clauses[0].guards.is_empty() {
            let clause = &clauses[0];
            let params: Vec<String> = (0..clause.patterns.len()).map(|i| format!("_arg{}", i)).collect();
            let params_str = params.join(", ");
            self.emit_indent();
            self.emit(&self.fn_decl(&lua_name, &params_str));
            self.emit("\n");
            self.indent += 1;

            let all_simple = clause.patterns.iter().all(|p| matches!(p, TPattern::Var(_, _) | TPattern::Wildcard));
            if all_simple {
                for (i, pat) in clause.patterns.iter().enumerate() {
                    if let TPattern::Var(v, _) = pat {
                        self.emit_line(&format!("local {} = _arg{}", v, i));
                    }
                }
                self.gen_where_binds(&clause.where_binds);
                if matches!(&clause.body.kind, TExprKind::Do(_)) {
                    self.gen_expr(&clause.body);
                } else {
                    self.emit_indent(); self.emit("return "); self.gen_expr(&clause.body); self.emit("\n");
                }
            } else {
                self.gen_where_binds(&clause.where_binds);
                self.gen_pattern_match(&params, clauses);
            }
            self.indent -= 1;
            self.emit_line("end");
            self.emit_line("");
            return;
        }

        // Multiple clauses or guards
        let num_params = clauses.iter().map(|c| c.patterns.len()).max().unwrap_or(0);
        let params: Vec<String> = (0..num_params).map(|i| format!("_arg{}", i)).collect();
        let params_str = params.join(", ");
        self.emit_indent();
        self.emit(&self.fn_decl(&lua_name, &params_str));
        self.emit("\n");
        self.indent += 1;
        self.gen_pattern_match(&params, clauses);
        self.indent -= 1;
        self.emit_line("end");
        self.emit_line("");
    }

    fn gen_where_binds(&mut self, binds: &[TLocalDef]) {
        // Group bindings by name to merge multi-clause local functions
        let mut i = 0;
        while i < binds.len() {
            let bind = &binds[i];
            if bind.patterns.is_empty() {
                // Simple value binding: local x = expr
                self.emit_indent();
                self.emit(&format!("local {} = ", sanitize_name(&bind.name)));
                self.gen_expr(&bind.body);
                self.emit("\n");
                i += 1;
            } else {
                // Collect all consecutive clauses with the same name
                let name = &bind.name;
                let mut clauses = Vec::new();
                let num_params = bind.patterns.len();
                while i < binds.len() && binds[i].name == *name && !binds[i].patterns.is_empty() {
                    clauses.push(TClause {
                        patterns: binds[i].patterns.clone(),
                        guards: vec![],
                        body: binds[i].body.clone(),
                        where_binds: vec![],
                    });
                    i += 1;
                }

                let params: Vec<String> = (0..num_params)
                    .map(|j| format!("_warg{}", j))
                    .collect();
                let params_str = params.join(", ");
                self.emit_indent();
                self.emit(&format!("local function {}({})\n",
                    sanitize_name(name), params_str));
                self.indent += 1;

                if clauses.len() == 1 {
                    let clause = &clauses[0];
                    let all_simple = clause.patterns.iter().all(|p|
                        matches!(p, TPattern::Var(_, _) | TPattern::Wildcard));

                    if all_simple {
                        for (j, pat) in clause.patterns.iter().enumerate() {
                            if let TPattern::Var(v, _) = pat {
                                self.emit_line(&format!("local {} = _warg{}", v, j));
                            }
                        }
                        self.emit_indent();
                        self.emit("return ");
                        self.gen_expr(&clause.body);
                        self.emit("\n");
                    } else {
                        self.gen_pattern_match(&params, &clauses);
                    }
                } else {
                    self.gen_pattern_match(&params, &clauses);
                }

                self.indent -= 1;
                self.emit_line("end");
            }
        }
    }

    fn gen_pattern_match(&mut self, params: &[String], clauses: &[TClause]) {
        for (i, clause) in clauses.iter().enumerate() {
            let keyword = if i == 0 { "if" } else { "elseif" };

            if !clause.guards.is_empty() {
                let mut bindings = Vec::new();
                let mut conditions = Vec::new();
                for (pi, pat) in clause.patterns.iter().enumerate() {
                    self.collect_pattern_conditions(&params[pi], pat, &mut conditions, &mut bindings);
                }
                if !conditions.is_empty() {
                    // Wrap in a pattern-matching if block, then test guards inside
                    self.emit_indent();
                    self.emit(&format!("{} {} then\n", keyword, conditions.join(" and ")));
                    self.indent += 1;
                    for (var, val) in &bindings {
                        self.emit_line(&format!("local {} = {}", var, val));
                    }
                    for (gi, guard) in clause.guards.iter().enumerate() {
                        let gkw = if gi == 0 { "if" } else { "elseif" };
                        self.emit_indent(); self.emit(&format!("{} ", gkw));
                        let mut sub = CodeGen::new();
                        sub.constructors = self.constructors.clone();
                        sub.newtypes = self.newtypes.clone();
                        sub.gen_expr(&guard.condition);
                        self.emit(&sub.output);
                        self.emit(" then\n");
                        self.indent += 1;
                        self.emit_indent(); self.emit("return "); self.gen_expr(&guard.body); self.emit("\n");
                        self.indent -= 1;
                    }
                    self.emit_line("end");
                    self.indent -= 1;
                } else {
                    // No pattern conditions, just guards
                    for (var, val) in &bindings {
                        self.emit_line(&format!("local {} = {}", var, val));
                    }
                    for (gi, guard) in clause.guards.iter().enumerate() {
                        let gkw = if i == 0 && gi == 0 { "if" } else { "elseif" };
                        self.emit_indent(); self.emit(&format!("{} ", gkw));
                        let mut sub = CodeGen::new();
                        sub.constructors = self.constructors.clone();
                        sub.newtypes = self.newtypes.clone();
                        sub.gen_expr(&guard.condition);
                        self.emit(&sub.output);
                        self.emit(" then\n");
                        self.indent += 1;
                        self.emit_indent(); self.emit("return "); self.gen_expr(&guard.body); self.emit("\n");
                        self.indent -= 1;
                    }
                }
            } else {
                let mut conditions = Vec::new();
                let mut bindings = Vec::new();
                for (pi, pat) in clause.patterns.iter().enumerate() {
                    self.collect_pattern_conditions(&params[pi], pat, &mut conditions, &mut bindings);
                }

                if conditions.is_empty() {
                    if i > 0 { self.emit_indent(); self.emit("else\n"); self.indent += 1; }
                    for (var, val) in &bindings {
                        self.emit_line(&format!("local {} = {}", var, val));
                    }
                    self.gen_where_binds(&clause.where_binds);
                    if matches!(&clause.body.kind, TExprKind::Do(_)) {
                        self.gen_expr(&clause.body);
                    } else {
                        self.emit_indent(); self.emit("return "); self.gen_expr(&clause.body); self.emit("\n");
                    }
                    if i > 0 { self.indent -= 1; self.emit_line("end"); }
                    return;
                }

                self.emit_indent();
                self.emit(&format!("{} {} then\n", keyword, conditions.join(" and ")));
                self.indent += 1;
                for (var, val) in &bindings {
                    self.emit_line(&format!("local {} = {}", var, val));
                }
                self.gen_where_binds(&clause.where_binds);
                if matches!(&clause.body.kind, TExprKind::Do(_)) {
                    self.gen_expr(&clause.body);
                } else {
                    self.emit_indent(); self.emit("return "); self.gen_expr(&clause.body); self.emit("\n");
                }
                self.indent -= 1;
            }
        }
        self.emit_line("end");
        self.emit_line("error(\"Non-exhaustive patterns\")");
    }

    fn collect_pattern_conditions(&self, scrutinee: &str, pattern: &TPattern, conditions: &mut Vec<String>, bindings: &mut Vec<(String, String)>) {
        match pattern {
            TPattern::Var(name, _) => { bindings.push((sanitize_name(name), scrutinee.to_string())); }
            TPattern::Wildcard => {}
            TPattern::LitPat(lit) => {
                let s = match lit {
                    TLiteral::Integer(n) => format!("{}", n),
                    TLiteral::Number(n) => format!("{}", n),
                    TLiteral::Str(s) => format!("\"{}\"", s),
                    TLiteral::Bool(b) => if *b { "true".into() } else { "false".into() },
                };
                conditions.push(format!("{} == {}", scrutinee, s));
            }
            TPattern::Constructor { name, args } => {
                if self.is_newtype(name) {
                    // Newtype: zero-cost wrapper, value is the inner type directly
                    for arg in args {
                        self.collect_pattern_conditions(scrutinee, arg, conditions, bindings);
                    }
                } else if let Some((tag, total, is_enum)) = self.constructor_info(name) {
                    if is_enum {
                        conditions.push(format!("{} == {}", scrutinee, tag));
                    } else if total > 1 {
                        conditions.push(format!("{}[1] == {}", scrutinee, tag));
                        for (i, arg) in args.iter().enumerate() {
                            self.collect_pattern_conditions(&format!("{}[{}]", scrutinee, i + 2), arg, conditions, bindings);
                        }
                    } else {
                        for (i, arg) in args.iter().enumerate() {
                            self.collect_pattern_conditions(&format!("{}[{}]", scrutinee, i + 1), arg, conditions, bindings);
                        }
                    }
                } else {
                    match name.as_str() {
                        "True" => conditions.push(format!("{} == true", scrutinee)),
                        "False" => conditions.push(format!("{} == false", scrutinee)),
                        "Nothing" | "[]" => conditions.push(format!("{} == nil", scrutinee)),
                        "Just" => {
                            conditions.push(format!("{} ~= nil", scrutinee));
                            if let Some(arg) = args.first() {
                                self.collect_pattern_conditions(scrutinee, arg, conditions, bindings);
                            }
                        }
                        ":" => {
                            // Cons pattern: x:xs
                            conditions.push(format!("{} ~= nil", scrutinee));
                            if args.len() >= 1 {
                                self.collect_pattern_conditions(
                                    &format!("__mll_head({})", scrutinee),
                                    &args[0], conditions, bindings);
                            }
                            if args.len() >= 2 {
                                self.collect_pattern_conditions(
                                    &format!("__mll_tail({})", scrutinee),
                                    &args[1], conditions, bindings);
                            }
                        }
                        _ => conditions.push(format!("{} == {}", scrutinee, name)),
                    }
                }
            }
            TPattern::Paren(inner) => self.collect_pattern_conditions(scrutinee, inner, conditions, bindings),
        }
    }

    fn gen_expr(&mut self, expr: &TExpr) {
        match &expr.kind {
            TExprKind::Var(name) => {
                match name.as_str() {
                    "otherwise" => self.emit("true"),
                    _ => self.emit(&sanitize_name(name)),
                }
            }
            TExprKind::Con(name) => {
                match name.as_str() {
                    "[]" => self.emit("nil"),
                    _ => self.emit(name),
                }
            }
            TExprKind::Lit(lit) => self.gen_literal(lit),
            TExprKind::App(func, arg) => {
                // Check for cons application: (:) x xs => __mll_cons(x, xs)
                if let TExprKind::App(inner_f, inner_arg) = &func.kind {
                    if let TExprKind::Con(name) = &inner_f.kind {
                        if name == ":" {
                            self.emit("__mll_cons(");
                            self.gen_expr(inner_arg);
                            self.emit(", ");
                            self.gen_expr(arg);
                            self.emit(")");
                            return;
                        }
                    }
                }

                // Collect all applied arguments
                let mut args = vec![arg.as_ref()];
                let mut f = func.as_ref();
                while let TExprKind::App(inner_f, inner_arg) = &f.kind {
                    args.push(inner_arg.as_ref());
                    f = inner_f.as_ref();
                }
                args.reverse();

                // Check if this is a partial application:
                // the result type is still a function type
                let remaining = count_arrows(&expr.ty);
                if remaining > 0 {
                    // Partial application — generate a closure
                    // Wrapped in () so it can be immediately called in Lua
                    let extra_params: Vec<String> = (0..remaining)
                        .map(|i| format!("_pa{}", i))
                        .collect();
                    self.emit(&format!("(function({})\n", extra_params.join(", ")));
                    self.indent += 1;
                    self.emit_indent();
                    self.emit("return ");
                    self.gen_expr(f);
                    self.emit("(");
                    for (i, a) in args.iter().enumerate() {
                        if i > 0 { self.emit(", "); }
                        self.gen_expr(a);
                    }
                    for p in &extra_params {
                        self.emit(", ");
                        self.emit(p);
                    }
                    self.emit(")\n");
                    self.indent -= 1;
                    self.emit_indent();
                    self.emit("end)");
                } else {
                    // Full application
                    self.gen_expr(f);
                    self.emit("(");
                    for (i, a) in args.iter().enumerate() {
                        if i > 0 { self.emit(", "); }
                        self.gen_expr(a);
                    }
                    self.emit(")");
                }
            }
            TExprKind::InfixApp { op, lhs, rhs } => {
                let lua_op = match op.as_str() {
                    "++" => "..", "&&" => "and", "||" => "or", "/=" => "~=",
                    ":" => {
                        self.emit("__mll_cons(");
                        self.gen_expr(lhs); self.emit(", "); self.gen_expr(rhs);
                        self.emit(")");
                        return;
                    }
                    "$" => {
                        self.gen_expr(lhs); self.emit("("); self.gen_expr(rhs); self.emit(")");
                        return;
                    }
                    "." => {
                        self.emit("(function(_x) return "); self.gen_expr(lhs);
                        self.emit("("); self.gen_expr(rhs); self.emit("(_x)) end)");
                        return;
                    }
                    other => other,
                };
                if !is_builtin_op(op) && op.chars().all(|c| c.is_alphanumeric() || c == '_') {
                    match op.as_str() {
                        "mod" => { self.emit("("); self.gen_expr(lhs); self.emit(" % "); self.gen_expr(rhs); self.emit(")"); }
                        "div" => { self.emit("("); self.gen_expr(lhs); self.emit(" // "); self.gen_expr(rhs); self.emit(")"); }
                        _ => {
                            self.emit(&sanitize_name(op)); self.emit("(");
                            self.gen_expr(lhs); self.emit(", "); self.gen_expr(rhs); self.emit(")");
                        }
                    }
                } else {
                    self.emit("("); self.gen_expr(lhs);
                    self.emit(&format!(" {} ", lua_op));
                    self.gen_expr(rhs); self.emit(")");
                }
            }
            TExprKind::Negate(inner) => { self.emit("(-"); self.gen_expr(inner); self.emit(")"); }
            TExprKind::If { cond, then_branch, else_branch } => {
                self.emit("(function()\n"); self.indent += 1;
                self.emit_indent(); self.emit("if "); self.gen_expr(cond); self.emit(" then\n");
                self.indent += 1; self.emit_indent(); self.emit("return "); self.gen_expr(then_branch); self.emit("\n"); self.indent -= 1;
                self.emit_indent(); self.emit("else\n");
                self.indent += 1; self.emit_indent(); self.emit("return "); self.gen_expr(else_branch); self.emit("\n"); self.indent -= 1;
                self.emit_indent(); self.emit("end\n"); self.indent -= 1;
                self.emit_indent(); self.emit("end)()");
            }
            TExprKind::Case { scrutinee, branches } => {
                self.emit("(function()\n"); self.indent += 1;
                self.emit_indent(); self.emit("local _s = "); self.gen_expr(scrutinee); self.emit("\n");
                for (i, branch) in branches.iter().enumerate() {
                    let mut conditions = Vec::new();
                    let mut bindings = Vec::new();
                    self.collect_pattern_conditions("_s", &branch.pattern, &mut conditions, &mut bindings);
                    if conditions.is_empty() {
                        if i > 0 { self.emit_indent(); self.emit("else\n"); self.indent += 1; }
                        for (var, val) in &bindings { self.emit_line(&format!("local {} = {}", var, val)); }
                        self.emit_indent(); self.emit("return "); self.gen_expr(&branch.body); self.emit("\n");
                        if i > 0 { self.indent -= 1; self.emit_line("end"); }
                        break;
                    }
                    let kw = if i == 0 { "if" } else { "elseif" };
                    self.emit_indent(); self.emit(&format!("{} {} then\n", kw, conditions.join(" and ")));
                    self.indent += 1;
                    for (var, val) in &bindings { self.emit_line(&format!("local {} = {}", var, val)); }
                    self.emit_indent(); self.emit("return "); self.gen_expr(&branch.body); self.emit("\n");
                    self.indent -= 1;
                    if i == branches.len() - 1 { self.emit_line("end"); }
                }
                self.indent -= 1; self.emit_indent(); self.emit("end)()");
            }
            TExprKind::Let { binds, body } => {
                self.emit("(function()\n"); self.indent += 1;
                for bind in binds {
                    self.emit_indent(); self.emit(&format!("local {} = ", bind.name));
                    self.gen_expr(&bind.body); self.emit("\n");
                }
                self.emit_indent(); self.emit("return "); self.gen_expr(body); self.emit("\n");
                self.indent -= 1; self.emit_indent(); self.emit("end)()");
            }
            TExprKind::Do(stmts) => {
                for (i, stmt) in stmts.iter().enumerate() {
                    match stmt {
                        TDoStmt::Bind { name, expr, .. } => {
                            self.emit_indent(); self.emit(&format!("local {} = ", name));
                            self.gen_expr(expr); self.emit("\n");
                        }
                        TDoStmt::DoLet { name, expr, .. } => {
                            self.emit_indent(); self.emit(&format!("local {} = ", name));
                            self.gen_expr(expr); self.emit("\n");
                        }
                        TDoStmt::Expr(expr) => {
                            if i == stmts.len() - 1 {
                                self.emit_indent(); self.emit("return "); self.gen_expr(expr); self.emit("\n");
                            } else {
                                self.emit_indent(); self.gen_expr(expr); self.emit("\n");
                            }
                        }
                    }
                }
            }
            TExprKind::Lambda { params, body } => {
                let ps: Vec<&str> = params.iter().map(|(s, _)| s.as_str()).collect();
                self.emit(&format!("function({})\n", ps.join(", ")));
                self.indent += 1; self.emit_indent(); self.emit("return ");
                self.gen_expr(body); self.emit("\n"); self.indent -= 1;
                self.emit_indent(); self.emit("end");
            }
            TExprKind::Paren(inner) => {
                self.emit("("); self.gen_expr(inner); self.emit(")");
            }
            TExprKind::OpFunc(op) => {
                let lua_op = match op.as_str() {
                    "++" => "..", "&&" => "and", "||" => "or", "/=" => "~=",
                    other => other,
                };
                self.emit(&format!("function(_a, _b) return _a {} _b end", lua_op));
            }
            TExprKind::SpecCall { specialized, args, .. } => {
                // Emit directly — could be a Lua FFI name like "math.sin"
                self.emit(specialized);
                self.emit("(");
                for (i, a) in args.iter().enumerate() {
                    if i > 0 { self.emit(", "); }
                    self.gen_expr(a);
                }
                self.emit(")");
            }
        }
    }

    /// Generate an expression with lazy cons tails for self-referencing definitions.
    /// Cons operations wrap the tail in a thunk via __mll_lazy_cons.
    fn gen_expr_lazy(&mut self, expr: &TExpr, self_name: &str) {
        // Check for infix cons: x : rest
        if let TExprKind::InfixApp { op, lhs, rhs } = &expr.kind {
            if op == ":" {
                self.emit("__mll_lazy_cons(");
                self.gen_expr(lhs);
                self.emit(", function() return ");
                self.gen_expr_lazy(rhs, self_name);
                self.emit(" end)");
                return;
            }
        }
        // Check for App(App(Con(":"), head), tail)
        if let TExprKind::App(func, tail) = &expr.kind {
            if let TExprKind::App(con, head) = &func.kind {
                if let TExprKind::Con(name) = &con.kind {
                    if name == ":" {
                        self.emit("__mll_lazy_cons(");
                        self.gen_expr(head);
                        self.emit(", function() return ");
                        self.gen_expr_lazy(tail, self_name);
                        self.emit(" end)");
                        return;
                    }
                }
            }
        }
        // Not a cons — fall through to normal gen
        self.gen_expr(expr);
    }

    fn gen_literal(&mut self, lit: &TLiteral) {
        match lit {
            TLiteral::Integer(n) => self.emit(&format!("{}", n)),
            TLiteral::Number(n) => self.emit(&format!("{}", n)),
            TLiteral::Str(s) => self.emit(&format!("\"{}\"", s)),
            TLiteral::Bool(true) => self.emit("true"),
            TLiteral::Bool(false) => self.emit("false"),
        }
    }
}

fn sanitize_name(name: &str) -> String {
    match name {
        "main" => "__run".to_string(),
        _ => name.replace('\'', "_prime").replace('-', "_"),
    }
}

/// Check if a TExpr references a given name anywhere
fn expr_references_name(expr: &TExpr, name: &str) -> bool {
    match &expr.kind {
        TExprKind::Var(n) => n == name,
        TExprKind::Con(_) | TExprKind::Lit(_) | TExprKind::OpFunc(_) => false,
        TExprKind::App(f, a) => expr_references_name(f, name) || expr_references_name(a, name),
        TExprKind::InfixApp { lhs, rhs, .. } => {
            expr_references_name(lhs, name) || expr_references_name(rhs, name)
        }
        TExprKind::Negate(e) | TExprKind::Paren(e) => expr_references_name(e, name),
        TExprKind::Lambda { body, .. } => expr_references_name(body, name),
        TExprKind::If { cond, then_branch, else_branch } => {
            expr_references_name(cond, name) ||
            expr_references_name(then_branch, name) ||
            expr_references_name(else_branch, name)
        }
        TExprKind::Case { scrutinee, branches } => {
            expr_references_name(scrutinee, name) ||
            branches.iter().any(|b| expr_references_name(&b.body, name))
        }
        TExprKind::Let { binds, body } => {
            binds.iter().any(|b| expr_references_name(&b.body, name)) ||
            expr_references_name(body, name)
        }
        TExprKind::Do(stmts) => stmts.iter().any(|s| match s {
            TDoStmt::Bind { expr, .. } | TDoStmt::DoLet { expr, .. } => expr_references_name(expr, name),
            TDoStmt::Expr(e) => expr_references_name(e, name),
        }),
        TExprKind::SpecCall { args, .. } => args.iter().any(|a| expr_references_name(a, name)),
    }
}

/// Count how many arrows are at the top level of a type.
/// Arrow(a, Arrow(b, c)) = 2, Arrow(a, b) = 1, Con(_) = 0
fn count_arrows(ty: &Ty) -> usize {
    match ty {
        Ty::Arrow(_, rest) => 1 + count_arrows(rest),
        _ => 0,
    }
}

fn is_builtin_op(op: &str) -> bool {
    matches!(op, "+" | "-" | "*" | "/" | "%" | "^" | "==" | "/=" | "~="
        | "<" | ">" | "<=" | ">=" | "++" | "&&" | "||" | ".." | "$" | ".")
}

pub fn generate(module: &TModule) -> String {
    let mut cg = CodeGen::new();
    cg.output.push_str(PRELUDE);
    cg.output.push('\n');
    cg.generate_module(module);
    cg.output
}

const PRELUDE: &str = r#"-- MLL Runtime

-- List primitives (internal)
local function __mll_cons(h, t) return {h, t} end
local function __mll_lazy_cons(h, thunk) return {h, thunk, __lazy = true} end
local function __mll_head(l) return l[1] end
local function __mll_tail(l)
    if l.__lazy then
        l[2] = l[2]()
        l.__lazy = nil
    end
    return l[2]
end

-- Primitives that require Lua runtime dispatch
local function engage(f) return f end
local function liftIO(action) return action end
local function show(x)
    if type(x) == "number" then return tostring(x)
    elseif type(x) == "string" then return x
    elseif type(x) == "boolean" then
        if x then return "True" else return "False" end
    elseif type(x) == "nil" then return "Nothing"
    elseif type(x) == "table" then
        if x[2] ~= nil or (x[1] ~= nil and type(x[2]) == "nil") then
            local parts = {}
            local cur = x
            local is_list = true
            while cur ~= nil do
                if type(cur) ~= "table" then is_list = false; break end
                parts[#parts + 1] = show(cur[1])
                cur = cur[2]
            end
            if is_list then return "[" .. table.concat(parts, ", ") .. "]" end
        end
        local parts = {}
        for i, v in ipairs(x) do parts[i] = show(v) end
        return "{" .. table.concat(parts, ", ") .. "}"
    else return tostring(x) end
end
local function error_(msg) error(msg) end
local function max(a, b) return math.max(a, b) end
local function min(a, b) return math.min(a, b) end
local function pure() end
local function Just(x) return x end
local Nothing = nil
local function show_Integer(x) return show(x) end
local function show_Number(x) return show(x) end
local function show_String(x) return show(x) end
local function show_Bool(x) return show(x) end
local function eq_Integer(a, b) return a == b end
local function eq_Number(a, b) return a == b end
local function eq_String(a, b) return a == b end
local function eq_Bool(a, b) return a == b end
local function ord_lt__Integer(a, b) return a < b end
local function ord_lt__Number(a, b) return a < b end
local function ord_lt__String(a, b) return a < b end
local function ord_gt__Integer(a, b) return a > b end
local function ord_gt__Number(a, b) return a > b end
local function ord_gt__String(a, b) return a > b end
local function ord_le__Integer(a, b) return a <= b end
local function ord_le__Number(a, b) return a <= b end
local function ord_le__String(a, b) return a <= b end
local function ord_ge__Integer(a, b) return a >= b end
local function ord_ge__Number(a, b) return a >= b end
local function ord_ge__String(a, b) return a >= b end
local function getArgs()
    local result = nil
    if arg then
        for i = #arg, 1, -1 do result = __mll_cons(arg[i], result) end
    end
    return result
end
local function exit_(code)
    if code == 1 then os.exit(0) else os.exit(code[2]) end
end
"#;
